spring:
  profiles:
    active: default
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: ExcelConvertorApplication
  data:
  pool:
        max-size: 50
        min-size: 5
  webflux:
    session:
      timeout: 6000s  # 10 minutes, adjust as needed
server:
  port: 8081
  reactive:
    session:
      timeout: 6000s  # 10 minutes, adjust as needed

logging:
  level:
    org:
      springframework:

        web:
          multipart: TRACE
com:
  amazonaws:
    sdk:
      enableDefaultMetrics: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
tesseract:
  datapath:  ${TESS_PATH:C:/Program Files/tess_5/tesseract/tessdata}
  lang-hin:  ${LANG:hin+eng}


pdf:
  directory: C:/voterData/
  output-directory: /path/to/output/excel/files
  dpi: 300
  batch-size: 5  # Process 5 files at a time
  thread-pool-size: 10  # Number of parallel threads
