spring:
  profiles:
    active: default
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: ExcelConvertorApplication
  data:
    mongodb:
      uri: mongodb://localhost:27017/voters
      #uri: mongodb+srv://admin:August%401599X@poll.p9umhu1.mongodb.net/voters?retryWrites=true&w=majority&socketTimeoutMS=1000000&connectTimeoutMS=100000&appName=Poll
      pool:
        max-size: 50
        min-size: 5
  webflux:
    session:
      timeout: 6000s  # 10 minutes, adjust as needed
server:
  port: 8082
  reactive:
    session:
      timeout: 6000s  # 10 minutes, adjust as needed

logging:
  level:
    org:
      springframework:

        web:
          multipart: TRACE
com:
  amazonaws:
    sdk:
      enableDefaultMetrics: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
tesseract:
  datapath:  ${TESS_PATH:C:\Program Files\tess_5\tesseract\tessdata}
  lang-hin:  ${LANG:hin}

pdf:
  dpi: 300
